"use strict";
exports.__esModule = true;
var Employee_1 = require("./Employee");
var Employee_2 = require("./Employee");
var EmployeeManager_1 = require("./EmployeeManager");
var employee1 = new Employee_1.Employee('Đoàn Ngọc Duy', Employee_2.Gender.MALE, new Date('1994-05-04'), 'duy.bk109@gmail.com', '0123456789');
var employee2 = new Employee_1.Employee('Đoàn Hùng Dũng', Employee_2.Gender.MALE, new Date('1992-08-21'), 'dung.neu@gmail.com', '0123356235');
var employeeManager = new EmployeeManager_1.EmployeeManager();
employeeManager.add(employee1);
employeeManager.add(employee2);
employeeManager["delete"](1);
console.log(employeeManager.getList());
